#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="/Users/openclawd/.openclaw/workspace/github/Openclaw"
TZ_REGION="America/Dawson_Creek"

cd "$REPO_DIR"

DATE_STR="$(TZ="$TZ_REGION" date +%F)"
NOW_STR="$(TZ="$TZ_REGION" date '+%Y-%m-%d %H:%M %Z')"
DAILY_DIR="docs/daily"
DAILY_FILE="$DAILY_DIR/$DATE_STR.md"

mkdir -p "$DAILY_DIR"

# Collect today's commits by this machine user (best effort)
COMMITS="$(git log --since "$DATE_STR 00:00:00" --until "$DATE_STR 23:59:59" --author="openclawd" --pretty=format:'- %h %s' || true)"

if [[ -z "$COMMITS" ]]; then
  COMMITS="- No commits recorded yet today."
fi

cat > "$DAILY_FILE" <<EOF
# Daily Log — $DATE_STR

_Last updated: ${NOW_STR}_

## What I did today

$COMMITS

## Notes

- Auto-generated by \`scripts/daily_log_and_push.sh\`.
- This file is refreshed daily and committed automatically.
EOF

# Commit only if there are changes (including first-time untracked file)
if [[ -n "$(git status --porcelain -- "$DAILY_FILE")" ]]; then
  git add "$DAILY_FILE"
  git commit -m "docs(daily): update $DATE_STR activity log"
  git push
fi
